apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-operator
  namespace: rabbitmq-operator
spec:
  selector:
    matchLabels:
      app: rabbitmq-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-operator
    spec:
      containers:
      - name: manager
        command:
        - /manager
        args:
        - --enable-leader-election
        image: ghcr.io/coderanger/rabbitmq-operator:latest
        resources:
          limits:
            cpu: 200m
            memory: 60M
          requests:
            cpu: 100m
            memory: 40M
      terminationGracePeriodSeconds: 10
      serviceAccount: rabbitmq-operator
