
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-operator-metrics
  namespace: rabbitmq-operator
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels: {}
