apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-operator-metrics
  namespace: rabbitmq-operator
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: rabbitmq-operator
