# permissions for end users to view rabbitvhosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitvhost-viewer-role
rules:
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitvhosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitvhosts/status
  verbs:
  - get
