# permissions for end users to view rabbitusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbituser-viewer-role
rules:
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitusers/status
  verbs:
  - get
