apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-operator
rules:
- apiGroups: [authentication.k8s.io]
  resources: [tokenreviews]
  verbs: [create]
- apiGroups: [authorization.k8s.io]
  resources: [subjectaccessreviews]
  verbs: [create]
- apiGroups:
  - ""
  resources:
  - secrets
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitqueues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitqueues/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitvhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.coderanger.net
  resources:
  - rabbitvhosts/status
  verbs:
  - get
  - patch
  - update
