apiVersion: v1
kind: Secret
metadata:
  name: {{ .Object.Name }}-rabbituser
  annotations:
    controller-utils/secretField: RABBIT_URL,RABBIT_URL_VHOST,RABBIT_USERNAME,RABBIT_HOSTNAME,RABBIT_PORT
data:
  RABBIT_URL: {{ .Data.uri | toString | b64enc | quote }}
  {{ if .Data.vhost }}
  RABBIT_URL_VHOST: {{ printf "%s%s" ( .Data.uri | toString ) .Data.vhost | b64enc | quote }}
  {{ end }}
  RABBIT_USERNAME: {{ .Data.username | toString | b64enc | quote }}
  RABBIT_HOSTNAME: {{ .Data.uri.Hostname | toString | b64enc | quote }}
