apiVersion: v1
kind: Secret
metadata:
  name: {{ .Object.Name }}-rabbituser
  annotations:
    controller-utils/secretField: RABBIT_HOST
data:
  RABBIT_HOST: {{ .Data.uri | toString | b64enc | quote }}
