# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/rabbitmq.coderanger.net_rabbitqueues.yaml
- bases/rabbitmq.coderanger.net_rabbitusers.yaml
- bases/rabbitmq.coderanger.net_rabbitvhosts.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/webhook_in_rabbitusers.yaml
- patches/webhook_in_rabbitvhosts.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch
- patches/cainjection_in_rabbitusers.yaml
- patches/cainjection_in_rabbitvhosts.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
